(unless (find-package :clog) (asdf:load-system :clog))
(defpackage :cl-db/main
  (:use :cl :clog)
  (:export #:main))
(in-package :cl-db/main)

(defparameter *fg*        "#e4e4ef")
(defparameter *fg+1*      "#f4f4ff")
(defparameter *fg+2*      "#f5f5f5")
(defparameter *white*     "#ffffff")
(defparameter *black*     "#000000")
(defparameter *bg-1*      "#101010")
(defparameter *bg*        "#181818")
(defparameter *bg+1*      "#282828")
(defparameter *bg+2*      "#453d41")
(defparameter *bg+3*      "#484848")
(defparameter *bg+4*      "#52494e")
(defparameter *red-1*     "#c73c3f")
(defparameter *red*       "#f43841")
(defparameter *red+1*     "#ff4f58")
(defparameter *green*     "#73c936")
(defparameter *yellow*    "#ffdd33")
(defparameter *brown*     "#cc8c3c")
(defparameter *quartz*    "#95a99f")
(defparameter *niagara-2* "#303540")
(defparameter *niagara-1* "#565f73")
(defparameter *niagara*   "#96a6c8")
(defparameter *wisteria*  "#9e95c7")

(defclass app ()
  ((menu-tab :initform :home :accessor menu-tab)
   (database :accessor database :initarg :database)))

(defun apply-header-bar-styling (obj)
  (setf (display obj) :flex)
  (setf (align-items obj) :center)
  ;; (setf (justify-content obj) :space-between)
  (setf (height obj) "56px")
  (setf (background-color obj) *bg+1*)
  (setf (color obj) *fg+1*)
  (setf (style obj "box-shadow") "0 2px 8px rgba(0, 0, 0, 0.15)")
  (setf (style obj "padding") 0)
  (setf (style obj "margin") 0)
  (setf (style obj "border-radius") "10px")
  (setf (style obj "padding-left") "10px"))

(defun apply-clickable-styling (obj)
  (setf (cursor obj) :pointer)
  (setf (color obj) *yellow*)
  (set-on-pointer-enter obj (lambda (obj) (setf (color obj) *white*)))
  (set-on-pointer-leave obj (lambda (obj) (setf (color obj) *yellow*)))
  (setf (style obj "padding") "5px")
  )



;;(defun database-create-tables (body db &optional second-try &aux stmt)
;;  (handler-case
;;      (progn
;;        (setf stmt (dbi:prepare db "create table customers(id integer primary key autoincrement);"))
;;        (dbi:execute stmt)
;;        )
;;    (sqlite-error ()
;;      (progn (clog:execute ))
;;      (setf stmt (dbi:prepare db "drop table customers;"))
;;      (dbi:execute stmt)
;;      ))
;;  )

(defun on-new-window (body)
  (setf (title (html-document body)) "CL-DB")
  (setf (style body "margin") "0px")
  (setf (style body "padding") "0px")
  (setf (font-css body) "normal 16px monospace")
  (setf (background-color body) *bg*)

  (let* ((app (make-instance 'app))
         (menu (create-div body))
         (contents (create-div body :style "padding:10px;"))
         (home-tab (create-section menu :h2 :content "home"))
         (open-orders-tab (create-section menu :h2 :content "open-orders"))
         )
    (setf (color contents) *fg*)
    (apply-header-bar-styling menu)
    
    (apply-clickable-styling (clog:create-a body :content "Click Me!" :link "/page2" ))
    
    (set-on-click home-tab (lambda (obj) (setf (menu-tab app) (html-id obj))))
    (set-on-click open-orders-tab (lambda (obj) (setf (menu-tab app) (html-id obj))))
    
    (apply-clickable-styling home-tab)
    (apply-clickable-styling open-orders-tab)

    (link-slot-to-element app menu-tab contents)

    ;;Refresh menu tab 
    (setf (menu-tab app) :foo)
    ))

(defun page2 (body)
  (create-section body :h1 :content "Hello from page2")
  )

(defun main()
  (initialize #'on-new-window)
  (set-on-new-window 'page2 :path "/page2")
  (open-browser)
  )
